name: Report to Slack

on:
  workflow_run:
    workflows: Test
    branches:
      - "*"
    types:
      - completed

jobs:
  report-to-slack:
    name: Report Failures to Slack
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLCAK_ALERT_WEBHOOK }}
