name: Test

on:
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    name: "${{ matrix.platform }} ${{ matrix.node-version }}"

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16.x, 17.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run test
        run: yarn ci

  report-failure:
    name: Report Failure to Slack
    needs:
      - build
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Report Status
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLCAK_ALERT_WEBHOOK }}
